### ISSUE TITLE
MESA adaptive moving average

### ISSUE THREAD

**Issue by b39647** [yungalyx/Luna6Algotrader#1]
Thank you,
Bhupen

**Comment by yungalyx** [comment]
Hi Bhupen,

I'm delighted to get this email from you!
Luna6 is just a personal project for me and I'm building it for school
so unfortunately I'm not allowed to have external contributions.
Thanks again for your interest!

Best,
Alexander

**Comment by b39647** [comment]
ok thanks

**Comment by b39647** [comment]
ok thanks
